services: 
  postgres:
    container_name: api-node-desafio
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio
